// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:f02eda5e-7b2d-4d63-8734-a629f4a555ec",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_jcHr2Rwn1",
    "aws_user_pools_web_client_id": "6bta32tikkmehie00cnk346si6",
    "oauth": {}
};


export default awsmobile;
