version: "3.7"
services:
    api: 
        container_name: api
        image: api
        networks:
          - postgres
        ports:
          - "3000:3000"
        build:
          context: api/
        depends_on:
          - db
        environment: 
          - DATABASE_URL=postgres://postgres:1KSA@fnc@db:5432/postgres
          - PORT=3000  
    db:
        container_name: postgres
        image: postgres
        volumes:
          - db-data:/var/lib/postgresql/data
        networks:
          - postgres
        ports:
          - "5432:5432"
        build: 
            context: Postgres/
    db-admin:
        container_name: pgadmin
        image: dpage/pgadmin4
        ports:
          - "5050:80"
        volumes:
          - db-admin:/pgdata
        networks:
          - postgres
        build:
            context: PgAdmin4
networks:
    postgres:
        driver: bridge
    
volumes:
    db-data:
    db-admin:
