version: "3.7"
services:
    db:
        image: postgres:postgres
        volumes:
          - db-data:/var/lib/postgresql/data
        networks:
          - postgres
        build: 
            context: Postgres/
    db-admin:
        image: dpage/pgadmin4:pgadmin
        ports:
          - "5050:80"
        volumes:
          - db-admin:/pgdata
        networks:
          - postgres
        build:
            context: PgAdmin4
networks:
    postgres:
    
volumes:
    db-data:
    db-admin:
