version: "3.7"
services:
  authentication_microservice:
    image: node:12-alpine
    working_dir: /app
    volumes:
      - ./api/authentication/:/app/
    command: sh -c "npm install && npm run dev"
  habits_microservice:
    image: node:12-alpine
    volumes:
      - ./api/habits:/app/
    working_dir: /app
    command: sh -c "npm install && npm run dev"
  users_microservice:
    image: node:12-alpine
    volumes:
      - ./api/users:/app/
    working_dir: /app
    command: sh -c "npm install && npm run dev"