version: "3.7"
services:
  habits_api:
    container_name: habits_api
    image: habits_api
    networks:
      - frontend
      - backend
    depends_on:
      - habits_db
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_POOL_ID=${AWS_POOL_ID}
      - DB_NETWORK=${DB_NETWORK}
      - DB_HOST=${HABIT_DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - PORT=3001
  habits_db:
    container_name: habits_db
    image: habits_db
    volumes:
      - habits-db-data:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      - PG_MODE=${DB_MODE}
      - PG_PRIMARY_USER=${DB_USER}
      - PG_PRIMARY_PASSWORD=${DB_PASSWORD}
      - PG_DATABASE=${DB_NAME}
      - PG_USER=${DB_ADMIN}
      - PG_PASSWORD=${DB_PASSWORD}
      - PG_ROOT_PASSWORD=${DB_PASSWORD}
    build: 
        context: habits/db/
  users_api:
    container_name: users_api
    image: users_api
    networks:
      - frontend
      - backend
    depends_on:
      - users_db
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_POOL_ID=${AWS_POOL_ID}
      - DB_NETWORK=${DB_NETWORK}
      - DB_HOST=${USER_DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - PORT=3002
  users_db:
    container_name: users_db
    image: users_db
    volumes:
      - users-db-data:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      - PG_MODE=${DB_MODE}
      - PG_PRIMARY_USER=${DB_USER}
      - PG_PRIMARY_PASSWORD=${DB_PASSWORD}
      - PG_DATABASE=${DB_NAME}
      - PG_USER=${DB_ADMIN}
      - PG_PASSWORD=${DB_PASSWORD}
      - PG_ROOT_PASSWORD=${DB_PASSWORD}
    build: 
        context: users/db/
  tasks_api:
    container_name: tasks_api
    image: tasks_api
    depends_on:
      - tasks_db
    networks:
      - frontend
      - backend
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_POOL_ID=${AWS_POOL_ID}
      - DB_NETWORK=${DB_NETWORK}
      - DB_HOST=${TASK_DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - PORT=3003
  tasks_db:
      container_name: tasks_db
      image: tasks_db
      volumes:
        - tasks-db-data:/var/lib/postgresql/data
      networks:
        - backend
      environment:
        - PG_MODE=${DB_MODE}
        - PG_PRIMARY_USER=${DB_USER}
        - PG_PRIMARY_PASSWORD=${DB_PASSWORD}
        - PG_DATABASE=${DB_NAME}
        - PG_USER=${DB_ADMIN}
        - PG_PASSWORD=${DB_PASSWORD}
        - PG_ROOT_PASSWORD=${DB_PASSWORD}
      build: 
          context: tasks/db/
  db-admin:
      container_name: pgadmin
      image: dpage/pgadmin4
      ports:
        - "5050:80"
      volumes:
        - db-admin:/pgdata
      networks:
        - backend
      environment:
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
  server:
      container_name: nginx
      image: nginx
      ports:
        - "37101:80"
      networks: 
        - frontend
      build:
          context: .
          dockerfile: nginx/DOCKERFILE
      depends_on:
        - habits_api
        - users_api
        - tasks_api
networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge
volumes:
    habits-db-data:
    tasks-db-data:
    users-db-data:
    db-admin: