version: "3.7"
services:
    db:
        container_name: postgres
        image: postgres
        volumes:
          - db-data:/var/lib/postgresql/data
        networks:
          - postgres
        ports:
          - "5432:5432"
        build: 
            context: Postgres/
    db-admin:
        container_name: pgadmin
        image: dpage/pgadmin4
        ports:
          - "5050:80"
        volumes:
          - db-admin:/pgdata
        networks:
          - postgres
        build:
            context: PgAdmin4
networks:
    postgres:
        driver: bridge
    
volumes:
    db-data:
    db-admin:
