version: "3.7"
services:
  tasks_api:
    image: node:12-alpine
    working_dir: /app
    volumes:
      - ./tasks/api:/app
    ports:
      - "9231:9229"
    command: sh -c "npm install && npm run dev"
  habits_api:
    image: node:12-alpine
    working_dir: /app
    volumes:
      - ./habits/api:/app
    ports:
      - "9229:9229"
    command: sh -c "npm install && npm run dev"
  users_microservice:
    image: node:12-alpine
    working_dir: /app
    volumes:
      - ./api/users:/app
    ports:
      - "9230:9229"
    command: sh -c "npm install && npm run dev"