version: "3.7"
services:
  habits_api:
    image: node:12-alpine
    working_dir: /app
    volumes:
      - ./habits:/app
    ports:
      - "9229:9229"
    command: sh -c "npm install && npm run dev"
  users_api:
    image: node:12-alpine
    working_dir: /app
    volumes:
      - ./users:/app
    ports:
      - "9230:9229"
    command: sh -c "npm install && npm run dev"
  tasks_api:
    image: node:12-alpine
    working_dir: /app
    volumes:
      - ./tasks:/app
    ports:
      - "9231:9229"
    command: sh -c "npm install && npm run dev"
  db:
    volumes:
      - db-data-dev:/var/lib/postgresql/data
  db-admin:
    volumes:
      - db-admin-dev:/pgdata
volumes:
    db-data-dev:
    db-admin-dev: