version: "3.7"
services:
  habits_api:
    container_name: habits_api
    image: habits_api
    networks:
      - frontend
      - backend
    depends_on:
      - db
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_POOL_ID=${AWS_POOL_ID}
      - DB_NETWORK=${DB_NETWORK}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${HABIT_DB_NAME}
      - DB_PORT=${DB_PORT}
      - PORT=3001
  users_api:
    container_name: users_api
    image: users_api
    networks:
      - frontend
      - backend
    depends_on:
      - db
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_POOL_ID=${AWS_POOL_ID}
      - DB_NETWORK=${DB_NETWORK}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${USER_DB_NAME}
      - DB_PORT=${DB_PORT}
      - PORT=3002
  tasks_api:
    container_name: tasks_api
    image: tasks_api
    depends_on:
      - db
    networks:
      - frontend
      - backend
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_POOL_ID=${AWS_POOL_ID}
      - DB_NETWORK=${DB_NETWORK}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${TASK_DB_NAME}
      - DB_PORT=${DB_PORT}
      - PORT=3003
  db:
    container_name: postgres
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      - PG_MODE=${DB_MODE}
      - PG_PRIMARY_USER=${DB_USER}
      - PG_PRIMARY_PASSWORD=${DB_PASSWORD}
      - PG_DATABASE=${DB_USER}
      - PG_USER=${DB_USER}
      - PG_PASSWORD=${DB_PASSWORD}
      - PG_ROOT_PASSWORD=${DB_PASSWORD}
    build: 
        context: database/
  db-admin:
      container_name: pgadmin
      image: dpage/pgadmin4
      ports:
        - "5050:80"
      volumes:
        - db-admin:/pgdata
      networks:
        - backend
      environment:
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
  server:
      container_name: nginx
      image: nginx
      ports:
        - "37101:80"
      networks: 
        - frontend
      build:
          context: .
          dockerfile: nginx/DOCKERFILE
      depends_on:
        - habits_api
        - users_api
        - tasks_api
networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge
volumes:
    db-data:
    db-admin: