version: "3.7"
services:
  cache:
    image: redis:buster
    container_name: cache
    networks:
      - backend
    command: redis-server
  tasks_api:
    container_name: tasks_api
    image: tasks_api
    volumes:
      - logs:${LOG_PATH}
    depends_on:
      - tasks_db
    networks:
      - frontend
      - backend
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_POOL_ID=${AWS_POOL_ID}
      - DB_NETWORK=${DB_NETWORK}
      - DB_HOST=${TASK_DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - PORT=3003
  tasks_db:
      container_name: tasks_db
      image: tasks_db
      volumes:
        - task-db-data:/var/lib/postgresql/tasks/data
      networks:
        - backend
      environment:
        - PG_MODE=${DB_MODE}
        - PG_PRIMARY_USER=${DB_USER}
        - PG_PRIMARY_PASSWORD=${DB_PASSWORD}
        - PG_DATABASE=${DB_NAME}
        - PG_USER=${DB_ADMIN}
        - PG_PASSWORD=${DB_PASSWORD}
        - PG_ROOT_PASSWORD=${DB_PASSWORD}
      build: 
          context: tasks/db/
  habits_microservice:
    container_name: habits
    image: habits
    volumes:
      - logs:${LOG_PATH}
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - cache
    environment:
      - CACHE_URL=${CACHE_URL}
      - DATABASE_URL=${DATABASE_URL}
      - PORT=3001
  users_microservice:
    container_name: users
    image: users
    volumes:
      - logs:/logs
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - cache
    environment:
      - CACHE_URL=${CACHE_URL}
      - DATABASE_URL=${DATABASE_URL}
      - LOG_PATH=${LOG_PATH}
      - PORT=3002
  db:
      container_name: postgres
      image: postgres
      volumes:
        - db-data:/var/lib/postgresql/data
      networks:
        - backend
      environment:
        - PG_MODE=${DB_MODE}
        - PG_PRIMARY_USER=${DB_USER}
        - PG_PRIMARY_PASSWORD=${DB_PASSWORD}
        - PG_DATABASE=${DB_NAME}
        - PG_USER=${DB_ADMIN}
        - PG_PASSWORD=${DB_PASSWORD}
        - PG_ROOT_PASSWORD=${DB_PASSWORD}
      build: 
          context: Postgres/
  db-admin:
      container_name: pgadmin
      image: dpage/pgadmin4
      ports:
        - "5050:80"
      volumes:
        - db-admin:/pgdata
      networks:
        - backend
      environment:
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
  server:
      container_name: nginx
      image: nginx
      ports:
        - "37101:80"
      networks: 
        - frontend
      build:
          context: .
          dockerfile: nginx/DOCKERFILE
      depends_on:
        - habits_microservice
        - users_microservice
        - tasks_api

networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge
    
volumes:
    task-db-data:
    db-data:
    db-admin:
    redis-cache:
    logs: