version: "3.7"
services:
  authentication_microservice:
    image: node:12-alpine
    working_dir: /app
    volumes:
      - ./api/authentication/:/app/
    ports:
      - "9231:9229"
    command: sh -c "npm install && npm run dev"
  habits_microservice:
    image: node:12-alpine
    volumes:
      - ./api/habits:/app/
    ports:
      - "9229:9229"
    working_dir: /app
    command: sh -c "npm install && npm run dev"
  users_microservice:
    image: node:12-alpine
    ports:
      - "9230:9229"
    volumes:
      - ./api/users:/app/
    working_dir: /app
    command: sh -c "npm install && npm run dev"