FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

#Copy files that will be served to the client
#COPY ./client/src/index.css /usr/share/nginx/html
#COPY ./client/src/index.html /usr/share/nginx/html

#TODO: Build React app and serve it
