CREATE TABLE UserProfile(
	UserID SERIAL PRIMARY KEY,
	Username VARCHAR(50) UNIQUE NOT NULL,
	Password VARCHAR(20) NOT NULL,
	CreatedOn TIMESTAMP NOT NULL,
	LastLogin TIMESTAMP NULL
);

CREATE TABLE Habit(
	HabitID SERIAL PRIMARY KEY,
	HabitDescription VARCHAR(50),
	HabitFrequency VARCHAR(20),
	Category VARCHAR(20)
);

CREATE TABLE UserHabitStat (
	UserHabitStatID SERIAL PRIMARY KEY,
	UserID INT NOT NULL,
	HabitID INT NOT NULL,
	FOREIGN KEY (UserID) REFERENCES UserProfile(UserID),
	FOREIGN KEY (HabitID) REFERENCES Habit(HabitID)
)
