#%RAML 1.0
title: User Habit API
baseUri: productivize.me/api
version: v1
types:
  UserHabit:
    type: object
    properties:
      UserName: string
      HabitDescription: string
      HabitFrequency: string

  UserProfile:
    type: object
    properties:
      UserID: string
      UserName: string
      CreatedOn: datetime
      LastLogin: datetime

/habits/GetAllUserHabits:
  get:
    queryParameters:
      userName:

/habit/InsertUserHabit:
  post:
    description: This POST operation will insert a user habit so the system can track it
    body:
      application/json:
        type: UserHabit
    
#GetHabits
#GetUser
#GetUserHabits
#GetUserStats

